### ISSUE TITLE
adding custom instructions

### ISSUE THREAD

**Issue by ada-flo** [stnolting/riscv-gcc-prebuilt#2]
I've been trying to add some custom instructions to this prebuilt toolchain (`rv64imc-3.0.0`),  which requires me to find opcode definitions in `riscv-opc.h` and `riscv-opc.c`. 

I've found that if you build the original toolchain, the above files could be found under `binutils/include/opcode` and `binutils/opcodes/riscv-opc.c`, respectively. 

However I've been struggling to find the `binutils` folder in the downloaded/extracted toolchain here, any help regarding where I might be able to find the folder or something that serves similar functionality?

**Comment by stnolting** [comment]
Hey there! I am no expert when it comes to modifying GCC... 🙈 But I do think you need to edits those files _before_ compiling GCC - as far as I know.

**Comment by stnolting** [comment]
FTR
An interesting overview of how to add custom instructions to RISC-V gcc: https://pcotret.gitlab.io/riscv-custom/
