### ISSUE TITLE
neorv32 example "hello_world" fails to build with rv32i-131023

### ISSUE THREAD

**Issue by rweeks** [stnolting/riscv-gcc-prebuilt#6]
When I follow the instructions [here](https://stnolting.github.io/neorv32/ug/#_hello_world) to build the neorv32 "hello world" example, the build fails with the error `extension 'zicsr' required`:

```
rweeks@dev-compiler-build:~/projects/neorv32/sw/example/hello_world$ make USER_FLAGS+="-DUART0_SIM_MODE -DUART1_SIM_MODE" MARCH=rv32imc clean_all sim
../../../sw/lib/include/neorv32_cpu.h: Assembler messages:
../../../sw/lib/include/neorv32_cpu.h:343: Error: unrecognized opcode `csrc 836,a0', extension `zicsr' required
../../../sw/lib/include/neorv32_cpu.h:329: Error: unrecognized opcode `csrs 772,a0', extension `zicsr' required
../../../sw/lib/include/neorv32_cpu.h:343: Error: unrecognized opcode `csrc 772,a0', extension `zicsr' required
../../../sw/lib/include/neorv32_cpu.h:343: Error: unrecognized opcode `csrc 836,a0', extension `zicsr' required
```

According to [this section of the neorv32 docs](https://stnolting.github.io/neorv32/#_zicsr_isa_extension), the `zicsr` extension is mandatory and can't ben enabled/disabled, so I'm not sure what's gone wrong.

Reverting to the 4.0.0 toolchain fixes the problem.

**Comment by rweeks** [comment]
setting the `MARCH` build parameter to `rv32imac_zicsr` fixes the problem.

**Comment by stnolting** [comment]
> setting the MARCH build parameter to rv32imac_zicsr fixes the problem.

Correct. The newer RISC-V GCC version do **not** include `Zicsr` "implicitly", hence `_zicsr` is required for the machine architecture string.

**Comment by stnolting** [comment]
This can be closed now, right?
